#+author: Jan Roßbach
#+title: rpass

* Rpass

This is a fairly simple gnu pass clone, written in rust.

* Dependencies

The following external programs are required.

- tree
- gpg
- gpgme
- libgpg-error

The dependencies come from the use of the [[https://github.com/gpg-rs/gpgm][gpgme]] and
[[https://github.com/gpg-rs/libgpg-error][libgpg-error]] crates. You can refer to them for hints on how to install these.

On arch you can just use the names to install via pacman.

* Motivation

As my first rust project, this is mostly in order to teach me the basics of rust.
I also wanted to extend the

* Usage

Exactly like you would expect from pass. All the commands should work as expected.

The location of the password store can be controlled with the `RPASSWORD_STORE_DIR` environment variable.
It defaults to `~/.password_store`. You can just re-use the your pass password store if you have one.

* Scripts

In the scripts folder of this repository you can find a updated version of passmenu called rpassmenu.
For those unfamiliar with passmenu, it is a dmenu script that lets you choose one of the passwords in the store
and copy it to the clipboard.
